#!/bin/csh

echo "Running tachyon with AO lighting"

# TCB lab install location
# setenv TACHYONBIN /Projects/vmd/pub/linux64/lib/vmd186b13/tachyon_LINUXAMD64

# typical install location
setenv TACHYONBIN /usr/local/lib/vmd/tachyon_LINUXAMD64 

set i = 1
while ( $i <= 10 )
   $TACHYONBIN  -trans_vmd  -rescale_lights 4.0 -add_skylight 2.0  -skylight_samples 4    21_${i}.dat     -fullshade  -res 1200 1200   -format PPM -o 21_${i}.ppm
   @ i++
end

$TACHYONBIN  -trans_vmd  -rescale_lights 4.0 -add_skylight 2.0  -skylight_samples 4    21.dat     -fullshade  -res 1200 1200   -format PPM -o 21.ppm

#-mediumshade -trans_vmd -normalize -normalize