#!/bin/csh

echo "Running tachyon with AO lighting"

# TCB lab install location
# setenv TACHYONBIN /Projects/vmd/pub/linux64/lib/vmd186b13/tachyon_LINUXAMD64

# typical install location
setenv TACHYONBIN /usr/local/lib/vmd/tachyon_LINUXAMD64 

set i = 10
while ( $i <= 20 )
   $TACHYONBIN  -trans_vmd  -rescale_lights 1.0 -add_skylight 0.9  -skylight_samples 8     ${i}.dat     -fullshade  -res 1600 1600   -format PPM -o capsule${i}.ppm
   @ i++
end


#-mediumshade -trans_vmd -normalize -normalize